projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/details.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/details.ts
        docsFilePath: src/graphql
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
